apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  labels:
    app: payments-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
        - name: payments-worker
          image: anafmel/paymentsworker:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            
            - name: AWS_ENDPOINT
              value: "http://localstack:4566"
            
            - name: ORDER_PLACED_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: payments-worker-config
                  key: ORDER_PLACED_QUEUE_NAME
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"